alias ..='cd ..'
alias ...='cd ../..'
alias -- +='pushd .'
alias -- -='popd'
alias cd..='cd ..'
alias dir='ls -l'
alias l='ls -alF'
alias la='ls -la'
alias ll='ls -l'
alias ls='ls -G -h'
alias ls-l='ls -l'
alias md='mkdir -p'
alias rd='rmdir'
alias less='less -R'
alias tm='tmux new-window'
alias vimpure='vim --noplugin -u /dev/null -n'
alias open='xdg-open'

# make tmux work with 256 colors
alias tmux="TERM=screen-256color-bce tmux"
