version: 2

root-markers:
  - .git/

tools:
  python-flake8: &python-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  sql-sqlfluff: &sql-sqlfluff
    lint-command: "sqlfluff lint --force --no-color"
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

languages:
  python:
    - <<: *python-flake8
    - <<: *python-mypy
  sql:
    - <<: *sql-sqlfluff
