version: 2

root-markers:
  - .git/

tools:
  python-flake8: &python-flake8
    lint-command: "flake8 --stdin-display-name ${INPUT} -"
    lint-stdin: true
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %m"

  python-mypy: &python-mypy
    lint-command: "mypy --show-column-numbers"
    lint-ignore-exit-code: true
    lint-formats:
      - "%f:%l:%c: %trror: %m"
      - "%f:%l:%c: %tarning: %m"
      - "%f:%l:%c: %tote: %m"

  sql-sqlfluff: &sql-sqlfluff
    lint-command: "sqlfluff lint --nocolor --disable_progress_bar"
    lint-ignore-exit-code: true
    lint-formats:
      - "L:%*[\ ]%l | P:%*[\ ]%c | L%.%# | %m"

languages:
  python:
    - <<: *python-flake8
    - <<: *python-mypy
  # XXX: Doesn't work reliably right now
  # sql:
    # - <<: *sql-sqlfluff
