require("plugins.plugins")

require("plugins.completion")
require("plugins.lsp")
require("plugins.diagnostics")
require("plugins.tree")
require("plugins.formatting")
require("plugins.testing")
require("plugins.colorscheme")
require("plugins.statusline")
require("plugins.fzf")
require("plugins.brackets")
require("plugins.git")
require("plugins.navigation")
require("plugins.misc")
